### ISSUE TITLE
Exception when printing a graph - Only on a browser

### ISSUE THREAD

**Issue by StatelessCat** [StatelessCat/simple-rdf.js#1]
https://github.com/StatelessCat/RDF-REST.JS/blob/master/src/graph.js#L91 
In a browser after browserification, 
# the context :
## promises

```
[]
```
## handler

```
function log() { [native code] }
```

This is console.log function
## s

```
Object {@id: "http://dbpedia.org/resource/John_Lennon"}
```
## p

```
Object {@id: "http://schema.org/birthDate"}
```
## c

```
Object {@id: "1940-10-09"}
```
# stacktrace

```
"TypeError: Illegal invocation
    at http://localhost:8080/public/js/rdfrestbundle.js:11163:51
    at Array.forEach (native)
    at forEachObject (http://localhost:8080/public/js/rdfrestbundle.js:11162:30)
    at forEachPredicate (http://localhost:8080/public/js/rdfrestbundle.js:11178:17)
    at Object.exports.graph.that.forEachTriple (http://localhost:8080/public/js/rdfrestbundle.js:11261:21)
    at http://localhost:8080/public/js/ng-index.js:22:15
    at http://localhost:8080/public/js/rdfrestbundle.js:10252:27
    at Array.flush (http://localhost:8080/public/js/rdfrestbundle.js:10544:21)
    at drainQueue (http://localhost:8080/public/js/rdfrestbundle.js:14736:32)"
```

**Comment by StatelessCat** [comment]
It's expected behavior. In the Chromium JavaScript V8 runtime, console.log cannot used like a function (and be run in a promise), because it assume the this is a reference to console, not window...

reference : http://stackoverflow.com/questions/8159233/typeerror-illegal-invocation-on-console-log-apply

We need to use

```
console.info.bind(console)
```

instead of 

```
console.log
```
